{% set name = "gelidum" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e02c6242c37eaeeca16a4d8e090a78907986f2ce320b3556d6f7fde6a86bdc1a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - gelidum
  requires:
    - pip
  commands:
    - pip check
    - python -m unittest discover -v gelidum

about:
  home: https://github.com/diegojromerolopez/gelidum
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Freeze your objects in Python
  description: |
    Inspired by the method freeze found in other languages like Javascript,
    this package tries to make immutable objects to make it easier avoiding
    accidental modifications in your code.
  dev_url: https://github.com/diegojromerolopez/gelidum

extra:
  recipe-maintainers:
    - diegojromerolopez
    - johnomotani
